import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./componets/Navbar";
import Footer from "./componets/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col justify-between h-[100dvh]">
        <Navbar/>      
        
        {children}
        <Footer />
      </body>
    </html>
  );
}
